labeler:
  issues:
    labels:
      - label1
      - label2
      - area:label3
    actions:
      - opened
      - milestoned
    at-least-one:
      labels:
        - priority:1
        - priority:2
        - priority:3
      default: priority:2

  pull-requests:
    labels:
      - label1
      - label2
    actions:
      - opened
      - synchronize

assigner:
  issues:
    project:
      id: 1
      column: To Do
    actions:
      - opened
      - milestoned
