name: Label PRs

on:
  - [pull_request, issues]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ppapapetrou76/virtual-assistant@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
