name: Label PRs

on: [issues, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ppapapetrou76/virtual-assistant@0.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
