name: Issues and PR Virtual Assistant

on: [issues, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ppapapetrou76/virtual-assistant@master
      env:
        GITHUB_TOKEN: "${{ secrets.ACTION_TOKEN }}"
